[package]
name = "handshake-types"
version = "0.1.0"
authors = ["kilpatty <sean@urkel.io>"]
edition = "2018"

[dependencies]
# Internal
handshake-encoding = { path="../encoding"}

# Known External
# extended-primitives = { git="https://github.com/UrkelLabs/extended-primitives.git" }
extended-primitives = "^0.2.0"
pds = { git="https://github.com/UrkelLabs/pds.git" }

# Unknown External
hex = "0.3.2"
chrono = "0.4"
cryptoxide = "0.1.1"
