[package]
name = "handshake_types"
version = "0.1.0"
authors = ["kilpatty <seanpkilgarriff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal
handshake_protocol = { path="../protocol"}

# Known External
extended-primitives = { git="https://github.com/UrkelLabs/extended-primitives.git" }
pds = { git="https://github.com/UrkelLabs/pds.git" }

# Unknown External
hex = "0.3.2"
chrono = "0.4"
