[package]
name = "handshake-encoding"
version = "0.1.2"
authors = ["kilpatty <sean@urkel.io>"]
edition = "2018"
license = "MIT"
description = "Encoding Library for Handshake"

[dependencies]

# Known External
extended-primitives = "^0.3.1"
encodings = "0.1.0"

